#!/bin/sh

export LC_NUMERIC="en_US.UTF-8"

MAX_VALUE=100
MIN_VALUE=10

backlight_current=$(printf "%.0f" $(xbacklight -get))
step=$1
backlight_target=$((backlight_current+step))

if (($backlight_target < $MIN_VALUE)); then
	backlight_target=$MIN_VALUE
fi

if (($backlight_target > $MAX_VALUE)); then
	backlight_target=$MAX_VALUE
fi

echo $backlight_target
xbacklight -time 100 -steps 10 -set $backlight_target
